  - hosts: all
    tasks:
      - name: "update apt"
        apt:
            update_cache: true
        become: true
      - name: "install Docker's prerequisites"
        apt:
            name: ["apt-transport-https", "ca-certificates", "curl", "gnupg-agent", "software-properties-common"]
        become: true
      - name: "add Docker's GPG key"
        apt_key:
            url: "https://download.docker.com/linux/ubuntu/gpg"
        become: true
      - name: "add Docker's repository"
        apt_repository:
            repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
                   {{ ansible_distribution_release }} stable"
        become: true
      - name: "update apt"
        apt:
            update_cache: true
        become: true
      - name: "install Docker"
        apt:
            name: ["docker-ce", "docker-ce-cli", "containerd.io"]
        become: true

        # enable using Docker as a non-root user
      - name: "create the 'docker' group"
        group:
            name: "docker"
            state: "present"
        become: true
      - name: "add current user to the 'docker' group"
        user:
            name: "{{ ansible_user_id }}"
            groups: "docker"
            append: true
        become: true
