  - hosts: all
    tasks:
      - name: "update apt"
        apt:
            update_cache: true
        become: true
      - name: "install prerequisites"
        apt:
            name: ["apt-transport-https", "curl"]
        become: true
      - name: "add apt key"
        apt_key:
            url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
        become: true
      - name: "add apt source"
        lineinfile:
            path: "/etc/apt/sources.list.d/kubernetes.list"
            line: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
            create: true
        become: true
      - name: "update apt"
        apt:
            update_cache: true
        become: true
      - name: "install packages"
        apt:
            name: ["kubeadm=1.15.4-00", "kubectl=1.15.4-00", "kubelet=1.15.4-00"]
        become: true
      - name: "prevent updating of the packages"
        command: "apt-mark hold kubeadm kubectl kubelet"
        become: true
