  - name: "get Kubernetes' dependencies"
    import_playbook: "get-dependencies.yaml"

  - hosts: all
    tasks:
      - name: "disable swap"
        command: "swapoff -a"
        become: true
      - name: "keep swap disabled after reboot"
        replace:
            path: "/etc/fstab"
            regexp: "^([^#].+\sswap\s+sw.*)$"
            replace: "# \1"
        become: true
      - name: "initialize cluster"
        command: "kubeadm init --pod-network-cidr={{ networks.kubernetes.cidr }}"
        become: true
      - name: "make Kubernetes configuration directory"
        file:
            path: "{{ ansible_env.HOME }}/.kube"
            state: "directory"
      - name: "copy Kubernetes configuration file"
        copy:
            src: "/etc/kubernetes/admin.conf"
            dest: "{{ ansible_env.HOME }}/.kube/config"
            owner: "{{ ansible_user_uid }}"
            group: "{{ ansible_user_gid }}"
            remote_src: true
        become: true
      - name: "generate pod network configuration"
        template:
            src: "../../conf/kubernetes/calico.yaml.j2"
            dest: "../../conf/kubernetes/calico.yaml"
      - name: "install pod network"
        command: "kubectl apply -f ../../conf/kubernetes/calico.yaml"
      - name: "allow pod scheduling on the master"
        command: "kubectl taint nodes --all node-role.kubernetes.io/master-"
      - name: "enable kubectl autocompletion"
        lineinfile:
            path: "{{ ansible_env.HOME }}/.bashrc"
            line: "source <(kubectl completion bash)"
