---
  - hosts: localhost
    vars_files:
      - "vars.yaml"
    tasks:
      - name: "render dhcp templates"
        block:
          - name: "create destination directory"
            file:
                path: "../dhcp-server/generated-configurations/"
                state: "directory"
          - name: "render dhcpd.conf template"
            template:
                src: "../dhcp-server/conf-templates/etc/dhcp/dhcpd.conf.j2"
                dest: "../dhcp-server/generated-configurations/dhcpd.conf"
