---
  - name: "install Docker"
    import_playbook: install-docker.yaml

  - hosts: localhost
    vars_files:
      - "vars.yaml"
    tasks:
        # install netaddr and the python library for docker
      - name: "download script for setting up pip"
        get_url:
            url: "https://bootstrap.pypa.io/get-pip.py"
            dest: "../get-pip.py"
      - name: "install pip"
        script: "../get-pip.py"
      - name: "install python library for docker"
        pip:
            name: "docker"
      - name: "install netaddr"
        pip:
            name: "netaddr"

      - name: "pull DHCP server source"
        git:
            repo: "https://github.com/AlassaneNdiaye/dhcp-server.git"
            dest: "../dhcp-server"

      - name: "pull PXE server source"
        git:
            repo: "https://github.com/AlassaneNdiaye/pxe-server.git"
            dest: "../pxe-server"
