---
  - hosts: localhost
    vars_files:
      - "vars.yaml"
    tasks:
      - name: "update apt"
        apt:
            update_cache: true
        become: true

        # install Docker
      - name: "install Docker's prerequisites"
        apt:
            name: ["apt-transport-https", "ca-certificates", "curl", "gnupg-agent", "software-properties-common"]
        become: true
      - name: "add Docker's GPG key"
        apt_key:
            url: "https://download.docker.com/linux/ubuntu/gpg"
      - name: "add Docker's repository"
        apt_repository:
            repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
                   {{ansible_distribution_release}} stable"
      - name: "update apt"
        apt:
            update_cache: true
        become: true
      - name: "install Docker"
        apt:
            name: ["docker-ce", "docker-ce-cli", "containerd.io"]
        become: true

        # install netaddr
      - name: "download script for setting up pip"
        get_url:
            url: "https://bootstrap.pypa.io/get-pip.py"
            dest: "/get-pip.py"
      - name: "install pip"
        script: "/get-pip.py"
      - name: "install netaddr"
        pip:
            name: "netaddr"

      - name: "download Ubuntu 16.04 iso"
        get_url:
            url: "http://releases.ubuntu.com/16.04/ubuntu-16.04.5-server-amd64.iso"
            dest: "/ubuntu-16.04.5-server-amd64.iso"
